export const ActionTypes = {
  TOGGLE_HAS_NOTY: "TOGGLE_HAS_NOTY",
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SET_CURRENT_USER_TV_PROFILE: "SET_CURRENT_USER_TV_PROFILE",
  SET_CURRENT_USER_XSTORE: "SET_CURRENT_USER_XSTORE",
  CURRENT_PAGE: "CURRENT_PAGE",
};
