import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
  },
  header: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    paddingTop: 40,
    paddingBottom: 15,
    paddingLeft: 20,
    paddingRight: 10,
    // zIndex: 1,
    minHeight: 80,
    backgroundColor: "#ffffff",
    justifyContent: "space-between",
    // elevation: 1,
  },
  circle: {
    alignItems: "center",
    justifyContent: "center",
    width: 30,
    height: 30,
    borderRadius: 20,
    marginLeft: 5,
    elevation: 2,
    backgroundColor: "#ffffff",
  },
  routeTitle: {
    color: "#111111",
    fontSize: 16,
    letterSpacing: 1,
  },
  userPreview: {
    flexDirection: "row",
    alignItems: "center",
    paddingRight: 50,
  },
  userImageContainer: {
    width: "40%",
    backgroundColor: "#006aff",
    padding: 10,
    borderTopRightRadius: 100,
    borderBottomRightRadius: 100,
    flexDirection: "row",
    justifyContent: "flex-end",
    marginVertical: 20,
  },
  userImage: {
    width: 80,
    height: 80,
    resizeMode: "cover",
    borderRadius: 50,
    borderWidth: 2,
    borderColor: "#fff",
  },
  usernameContainer: {
    flexDirection: "row",
    alignItems: "flex-start",
  },
  username: {
    color: "#42414C",
    fontSize: 22,
    fontWeight: "600",
    marginBottom: 5,
    marginLeft: -2,
    letterSpacing: 1,
  },
  fufBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 30,
    paddingVertical: 8,
    marginVertical: 10,
    // borderWidth: 1.5,
    borderRadius: 20,
    // borderColor: "#006aff",
    elevation: 3,
  },
  fufBtnText: {
    color: "#006aff",
    letterSpacing: 1,
    textTransform: "uppercase",
    fontSize: 10,
    fontWeight: "bold",
  },
  title: {
    color: "#42414C",
    fontSize: 16,
    // marginLeft: 10,
    fontWeight: "bold",
    marginBottom: 1,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  centerContainer: {
    position: "absolute",
    top: 90,
    bottom: 0,
    right: 0,
    left: 0,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  customDialogTitle: {
    paddingVertical: 5,
    borderBottomColor: "#44444444",
    borderBottomWidth: 1,
    width: "100%",
    marginBottom: 10,
  },
  customDialogBody: {
    // alignSelf: "center",
    flex: 1,
    // justifyContent: "center",
  },
  modalTextButton: {
    marginVertical: 3,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  modalText: {
    color: "#111111",
    fontWeight: "600",
    fontSize: 15,
  },
  focusedText: {
    color: "#006eff",
    fontSize: 9,
    fontWeight: "bold",
    letterSpacing: 1,
    marginTop: 5,
    textTransform: "uppercase",
    textAlign: "center",
  },
  noPostContainerWrapper: {
    minHeight: 150,
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  noPostContainer: {
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  noPost: {
    position: "absolute",
    fontWeight: "100",
  },
  listReels: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 20,
  },
  moreModalContainer: {
    position: "absolute",
    zIndex: 5,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: "flex-end",
    backgroundColor: "transparent",
    paddingTop: 85,
  },
  listReels: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 20,
  },
  buttonContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "transparent",
  },
  button: {
    flexDirection: "row",
    backgroundColor: "#006eff",
    elevation: 2,
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  buttonText: {
    color: "#111111",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
    marginRight: 5,
  },
});
