export const ActionTypes = {
  SET_CURRENT_CHANNEL: "SET_CURRENT_CHANNEL",
  SET_FRIENDS: "SET_FRIENDS",
  SET_CHAT_BACKGROUND: "SET_CHAT_BACKGROUND",
  SET_PRIVATE_CHANNEL: "SET_PRIVATE_CHANNEL",
  SET_USER_POSTS: "SET_USER_POSTS",
  SET_COLORS: "SET_COLORS",
};
