import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "transparent",
  },
  header: {
    flexDirection: "row",
    width: "100%",
    alignItems: "center",
    paddingTop: 20,
    paddingBottom: 10,
    paddingHorizontal: 20,
    zIndex: 1,
    minHeight: 80,
    backgroundColor: "transparent",
    justifyContent: "space-between",
  },
  userPreview: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#00000095",
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    marginTop: "auto",
  },
  title: {
    color: "#444444",
    fontSize: 16,
    marginLeft: 10,
    marginBottom: 1,
  },
  tvHandle: {
    color: "#ffffff",
    fontSize: 20,
    fontWeight: "500",
    fontWeight: "bold",
  },
  centerContainer: {
    position: "absolute",
    top: 90,
    bottom: 0,
    right: 0,
    left: 0,
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    // backgroundColor: "#000000",
    // opacity: 0.5,
    zIndex: 1,
  },
  customDialogTitle: {
    paddingVertical: 10,
    borderBottomColor: "#44444444",
    borderBottomWidth: 1,
    width: "100%",
  },
  modalTextButton: {
    marginVertical: 3,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
  },
  modalText: {
    color: "#111111",
    fontWeight: "600",
    fontSize: 15,
  },
  listReels: {
    flexDirection: "row",
    justifyContent: "space-between",
    flexWrap: "wrap",
    paddingHorizontal: 10,
    paddingVertical: 10,
    paddingBottom: 20,
  },
  customDialogTitle: {
    paddingVertical: 10,
    borderBottomColor: "#44444444",
    borderBottomWidth: 1,
  },
  customDialogBody: {
    alignSelf: "center",
    flex: 1,
    justifyContent: "center",
  },
  buttonContainer: {
    position: "absolute",
    bottom: 20,
    right: 20,
  },
  button: {
    flexDirection: "row",
    backgroundColor: "#006eff",
    elevation: 2,
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    width: 50,
    borderRadius: 25,
  },
  buttonText: {
    color: "#111111",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
    marginRight: 5,
  },
});
