import { StyleSheet } from "react-native";

const BAR_HEIGHT = StyleSheet.hairlineWidth * 5;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
    backgroundColor: "black",
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    right: 5,
    position: "absolute",
    top: 30,
    left: 20,
    zIndex: 1,
  },
  preview: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  backBtn: {
    alignItems: "center",
    justifyContent: "center",
    width: 35,
    height: 35,
    borderRadius: 20,
    elevation: 2,
    backgroundColor: "#ffffff",
  },
  postToContainer: {
    alignItems: "flex-end",
    justifyContent: "center",
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRadius: 30,
  },
  postTo: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#006eff",
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRadius: 30,
  },
  postToImage: {
    height: 35,
    width: 35,
    borderRadius: 20,
  },
  postToText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "bold",
    letterSpacing: 1,
    marginLeft: 5,
    marginRight: 5,
  },
  recordControl: {
    position: "absolute",
    width: "100%",
    bottom: 60,
    flexDirection: "row",
    justifyContent: "center",
  },
  progressBarContainer: {
    width: "90%",
    height: BAR_HEIGHT,
    borderRadius: BAR_HEIGHT / 2,
    backgroundColor: "rgba(255,255,255,0.4)",
    overflow: "hidden",
    position: "absolute",
    bottom: -5,
  },

  progressBar: {
    height: "100%",
    width: "100%",
    borderRadius: BAR_HEIGHT / 2,
    backgroundColor: "red",
  },
  recordControlWrapper: {
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    width: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: "#ff4343",
    backgroundColor: "transparent",
  },
  buttonRecord: {
    alignSelf: "center",
    height: 50,
    width: 50,
    borderRadius: 25,
    backgroundColor: "#ff4343",
  },
  buttonStop: {
    height: 20,
    width: 20,
    borderRadius: 3,
    backgroundColor: "#ff4343",
  },
  storyTypes: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRadius: 30,
  },
  storyType: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRadius: 30,
  },
  storyTypeIconWrapper: {
    borderWidth: 2,
    borderColor: "#006eff",
    width: 45,
    height: 45,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 30,
    backgroundColor: "#ffffff78",
  },
  storyTypeTextWrapper: {
    paddingHorizontal: 3,
    paddingVertical: 3,
    borderRadius: 30,
    marginVertical: 5,
    backgroundColor: "#ffffff78",
  },
  storyTypeText: {
    color: "#000000",
    fontSize: 12,
    fontWeight: "bold",
    letterSpacing: 1,
    marginLeft: 5,
    marginRight: 5,
  },
  otherControl: {
    position: "absolute",
    bottom: 40,
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 20,
  },
  otherControlWrapper: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#00000096",
    borderRadius: 50,
  },
  selectFromPhone: {
    padding: 1,
    borderRadius: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  flipCamera: {
    backgroundColor: "#ffffff89",
    // padding: 5,
    height: 40,
    width: 40,
    // paddingHorizontal: 6,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
  },
  assets: {
    position: "absolute",
    bottom: 120,
    left: 0,
    right: 0,
    minHeight: 80,
  },
});

export default styles;
